[book]
authors = ["Sirius Wu"]
language = "zh-TW"
src = "src"
title = "Botnana Control"
description = "The Official User Manual"

[preprocessor.toc]
command = "mdbook-toc"
optional = true
renderer = ["html"]

[output.html]

[output.html.print]
enable = true

[output.pdf]
